# Generated by Django 5.1.2 on 2024-10-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desperdicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.FloatField()),
                ('hotel', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
    ]
